/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  logo: require('App/Assets/Images/yeep-logo-2.png'),
  organizer: require('App/Assets/Images/event_planner.jpg'),
  service_provider: require('App/Assets/Images/service_provider.jpg'),
  image_background: require('App/Assets/Images/image-background.png'),
  error: require('App/Assets/Images/error.jpg'),
  coming_soon: require('App/Assets/Images/coming-soon.jpg'),
  empty: require('App/Assets/Images/empty.png'),
  not_found: require('App/Assets/Images/not-found.png'),

  // ANIMATIONS
  editing_animation: require('App/Assets/Images/editing-animation.json'),
  yeep_loading: require('App/Assets/Images/yeep-loading.json'),
  
  // ICONS
  profile_boy: require('App/Assets/Images/profile-boy.png'),
  button_remove: require('App/Assets/Images/button-remove.png'),
  cancel: require('App/Assets/Images/cancel.png'),
  check_mark: require('App/Assets/Images/check-mark.png'),
  heart_fill: require('App/Assets/Images/heart-fill.png'),
  heart_not_fill: require('App/Assets/Images/heart-not-fill.png'),
  located: require('App/Assets/Images/located.png'),
  square_clock: require('App/Assets/Images/square-clock.png'),
  negociations_icon: require('App/Assets/Images/negociations.png'),
  pencil: require('App/Assets/Images/pencil.png'),
  dj_active: require('App/Assets/Images/dj-active.png'),
  dj_inactive: require('App/Assets/Images/dj-inactive.png'),
  my_event_active: require('App/Assets/Images/my-event-active.png'),
  my_event_inactive: require('App/Assets/Images/my-event-inactive.png'),
  negociation_active: require('App/Assets/Images/negociation-active.png'),
  negociation_inactive: require('App/Assets/Images/negociation-inactive.png'),
  notification_active: require('App/Assets/Images/notification-active.png'),
  notification_inactive: require('App/Assets/Images/notification-inactive.png'),
  place_active: require('App/Assets/Images/place-active.png'),
  place_inactive: require('App/Assets/Images/place-inactive.png'),
  coins: require('App/Assets/Images/coins.png'),
  group: require('App/Assets/Images/group.png'),
  
  // ORGANIZER STEPs
  organizerStepOne: require('App/Assets/Images/organizer-step-1.png'),
  organizerStepTwo: require('App/Assets/Images/organizer-step-2.png'),
  organizerStepThree: require('App/Assets/Images/organizer-step-3.png'),
  organizerStepFour: require('App/Assets/Images/organizer-step-4.png'),
  organizerStepFive: require('App/Assets/Images/organizer-step-5.png'),

  // SPACE CATEGORIES AND FILTERS
  allSpaceActive: require('App/Assets/Images/allSpaceActive.png'),
  allSpaceInactive: require('App/Assets/Images/allSpaceInactive.png'),
  barnFarmRanchActive: require('App/Assets/Images/barnFarmRanchActive.png'),
  barnFarmRanchInactive: require('App/Assets/Images/barnFarmRanchInactive.png'),
  pubActive: require('App/Assets/Images/pubActive.png'),
  pubInactive: require('App/Assets/Images/pubInactive.png'),
  meetingRoomActive: require('App/Assets/Images/meetingRoomActive.png'),
  meetingRoomInactive: require('App/Assets/Images/meetingRoomInactive.png'),
  boatActive: require('App/Assets/Images/boatActive.png'),
  boatInactive: require('App/Assets/Images/boatInactive.png'),
  churchTempleActive: require('App/Assets/Images/churchTempleActive.png'),
  churchTempleInactive: require('App/Assets/Images/churchTempleInactive.png'),
  classroomActive: require('App/Assets/Images/classroomActive.png'),
  classroomInactive: require('App/Assets/Images/classroomInactive.png'),
  coworkingSpaceActive: require('App/Assets/Images/coworkingSpaceActive.png'),
  coworkingSpaceInactive: require('App/Assets/Images/coworkingSpaceInactive.png'),
  cruiseShipYachtActive: require('App/Assets/Images/cruiseShipYachtActive.png'),
  cruiseShipYachtInactive: require('App/Assets/Images/cruiseShipYachtInactive.png'),
  eventVenuePartyHallActive: require('App/Assets/Images/eventVenuePartyHallActive.png'),
  eventVenuePartyHallInactive: require('App/Assets/Images/eventVenuePartyHallInactive.png'),
  gallerieActive: require('App/Assets/Images/gallerieActive.png'),
  gallerieInactive: require('App/Assets/Images/gallerieInactive.png'),
  houseActive: require('App/Assets/Images/houseActive.png'),
  houseInactive: require('App/Assets/Images/houseInactive.png'),
  hotelResortActive: require('App/Assets/Images/hotelResortActive.png'),
  hotelResortInactive: require('App/Assets/Images/hotelResortInactive.png'),
  loftActive: require('App/Assets/Images/loftActive.png'),
  loftInactive: require('App/Assets/Images/loftInactive.png'),
  mansionActive: require('App/Assets/Images/mansionActive.png'),
  mansionInactive: require('App/Assets/Images/mansionInactive.png'),
  parkGardenActive: require('App/Assets/Images/parkGardenActive.png'),
  parkGardenInactive: require('App/Assets/Images/parkGardenInactive.png'),
  restaurantActive: require('App/Assets/Images/restaurantActive.png'),
  restaurantInactive: require('App/Assets/Images/restaurantInactive.png'),
  stadiumActive: require('App/Assets/Images/stadiumActive.png'),
  stadiumInactive: require('App/Assets/Images/stadiumInactive.png'),
  studioActive: require('App/Assets/Images/studioActive.png'),
  studioInactive: require('App/Assets/Images/studioInactive.png'),
  theaterActive: require('App/Assets/Images/theaterActive.png'),
  theaterInactive: require('App/Assets/Images/theaterInactive.png'),
  warehouseActive: require('App/Assets/Images/warehouseActive.png'),
  warehouseInactive: require('App/Assets/Images/warehouseInactive.png'),
  parkingActive: require('App/Assets/Images/parkingActive.png'),
  parkingInactive: require('App/Assets/Images/parkingInactive.png'),
  perDayActive: require('App/Assets/Images/perDayActive.png'),
  perDayInactive: require('App/Assets/Images/perDayInactive.png'),
  perHourActive: require('App/Assets/Images/perHourActive.png'),
  perHourInactive: require('App/Assets/Images/perHourInactive.png'),
}
